# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description',
            field=models.CharField(default='short description here', max_length=128),
            preserve_default=False,
        ),
    ]
