# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_auto_20160516_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.Level'),
        ),
        migrations.AlterField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
