# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-07 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0007_auto_20160522_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='required_points',
            field=models.IntegerField(default=0),
        ),
    ]
