# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 23:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("levels", "0009_auto_20171005_1919"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="javascript",
            field=models.TextField(
                blank=True,
                help_text="This field will be inserted into the level page as JavaScript",
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="css",
            field=models.TextField(
                blank=True,
                help_text="This field will be inserted into the level page as CSS",
            ),
        ),
    ]
