# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("levels", "0011_auto_20171005_2340"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="required_attempts",
            field=models.IntegerField(
                default=0,
                help_text="Users need to try at least this many times before we accept an answer",
            ),
        ),
    ]
