# Generated by Django 6.0 on 2026-01-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("levels", "0013_auto_20171006_1645"),
    ]

    operations = [
        migrations.AddField(
            model_name="level",
            name="show_points",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, the amount of points this level is worth will be shown on the level list",
            ),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="level",
            name="question",
            field=models.TextField(
                blank=True,
                help_text="Question-text. Can be empty, but then you should have some other way (image?) for users to understand the question.",
            ),
        ),
        migrations.AlterField(
            model_name="score",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
